version: "2"
services:
  frontend:
    # restart: always
    build:
      context: .
      args:
        NODE_ENV: development
    env_file: ./env/front.dev.env
    ports:
      - "8080:8080"
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
      - ./public:/app/public
      - ./src:/app/src
