export const CHARACTER_GROUPS_REQUEST = 'CHARACTER_GROUPS_REQUEST';
export const CHARACTER_GROUPS_SUCCESS = 'CHARACTER_GROUPS_SUCCESS';
export const CHARACTER_GROUPS_ERROR = 'CHARACTER_GROUPS_ERROR';

export const CHARACTER_TAGS_REQUEST = 'CHARACTER_TAGS_REQUEST';
export const CHARACTER_TAGS_SUCCESS = 'CHARACTER_TAGS_SUCCESS';
export const CHARACTER_TAGS_ERROR = 'CHARACTER_TAGS_ERROR';

export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST';
export const CHARACTERS_SUCCESS = 'CHARACTERS_SUCCESS';
export const CHARACTERS_ERROR = 'CHARACTERS_ERROR';
